apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jesteruct.fullname" . }}
  labels:
    {{- include "jesteruct.labels" . | nindent 4 }}
data:
  {{- if not .Values.valkeyPassword.existingSecret }}
  JST_VALKEY_URL: {{ required "valkeyUrl is required" .Values.valkeyUrl | quote }}
  {{- end }}
  JST_STORE_URL: {{ required "storeUrl is required" .Values.storeUrl | quote }}
  {{- with .Values.storeConfig }}
  JST_STORE_CONFIG: {{ toJson . | quote }}
  {{- end }}
  {{- with .Values.storeClientOptions }}
  JST_STORE_CLIENT_OPTIONS: {{ toJson . | quote }}
  {{- end }}
  JST_STREAM: {{ .Values.queue.stream | quote }}
  JST_GROUP: {{ .Values.queue.group | quote }}
  JST_WORKER_MAX_DOCS: {{ .Values.worker.maxDocs | quote }}
  {{- range $name, $value := .Values.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
